### ISSUE TITLE
Compiled Elm code missing from heroku

### ISSUE THREAD

**Issue by finnhodgkin** [dwyl/hapi-socketio-redis-chat-example#100]
We added app.js - the compiled Elm code - to .gitignore to stop the git diffs from being huge on every commit involving Elm code. This should be fixed so the live heroku version has the Elm route (/elm).

**Comment by nelsonic** [comment]
@finnhodgkin the/my _preferred_ solution to this is _not_ to include the "_noisy_" compiled version of the code in git but rather to _build_ the elm version on Heroku `before` running the app...

**Comment by nelsonic** [comment]
before:
![image](https://user-images.githubusercontent.com/194400/28201495-3399e9e8-6869-11e7-871f-dcda21292a4e.png)

**Comment by nelsonic** [comment]
Deployed branch:
![image](https://user-images.githubusercontent.com/194400/28201590-a9bf4aaa-6869-11e7-8f8c-375b47a502b6.png)

Get `503` error in logs because of lack of `/favicon.ico` 😮  😞

**Comment by nelsonic** [comment]
_Attempted_ to use Heroku Buildpack for Elm apps: https://github.com/srid/heroku-buildpack-elm
got:
![image](https://user-images.githubusercontent.com/194400/28202196-27ff6934-686c-11e7-8cab-f9776004cdc1.png)

```
-----> Elm app detected
-----> Retrieving 0.18.0
2017-07-14 07:10:41 URL:https://s3.amazonaws.com/heroku-buildpack-elm/assets/elm/0.18.0/elm [1311192/1311192] -> "elm" [1]
2017-07-14 07:10:41 URL:https://s3.amazonaws.com/heroku-buildpack-elm/assets/elm/0.18.0/elm-package [6792960/6792960] -> "elm-package" [1]
2017-07-14 07:10:42 URL:https://s3.amazonaws.com/heroku-buildpack-elm/assets/elm/0.18.0/elm-make [10042432/10042432] -> "elm-make" [1]
-----> Fetching dependencies
       Starting downloads...
       
         ● elm-lang/dom 1.1.1
         ● elm-lang/core 5.1.1
         ● elm-lang/html 2.0.0
         ● NoRedInk/elm-decode-pipeline 3.0.0
         ● elm-lang/http 1.0.0
         ● elm-lang/virtual-dom 2.0.4
         ● elm-lang/window 1.0.1
         ● justinmimbs/elm-date-extra 2.0.3
       
       Packages configured successfully!
 !     Push rejected, failed to compile Elm app.
 !     Push failed
```

**Comment by nelsonic** [comment]
Read through previous issues on: https://github.com/srid/heroku-buildpack-elm/issues
found: https://github.com/srid/heroku-buildpack-elm/issues/5
which suggests that using an `app.json` file _might_ solve the issue ... 🤔 

examples of `app.json` files:
+ https://github.com/anicholson/elm-hangman/blob/master/app.json
+ https://github.com/mdgriffith/elm-electron-todomvc/blob/master/app.json

**Comment by nelsonic** [comment]
Build (_with `elm make`_) succeeds on Heroku with the addition of `app.json`:
![image](https://user-images.githubusercontent.com/194400/28202912-5fc76d96-686f-11e7-925f-d849e0599d8d.png)

_However_ the app still crashes because `npm start` is still trying to `elm-make` before starting:
![image](https://user-images.githubusercontent.com/194400/28202943-7e05beac-686f-11e7-93bf-4b074153bfec.png)

**Comment by nelsonic** [comment]
Logs look promising:
![image](https://user-images.githubusercontent.com/194400/28203042-e6db4d98-686f-11e7-81d2-4c4d19e7a89a.png)

**Comment by nelsonic** [comment]
https://hapi-chat.herokuapp.com/elm (_working on heroku_):
![image](https://user-images.githubusercontent.com/194400/28203099-18b8a0d6-6870-11e7-8f56-d85d803c17c9.png)

cc: @finnhodgkin

**Comment by finnhodgkin** [comment]
Awesome, thanks for sorting it! _Definitely_ a better solution than committing the compiled JS.

![chat - google chrome_001](https://user-images.githubusercontent.com/22300773/28203974-e6412bba-6873-11e7-9dff-e4836cfc33ca.png)

The elm version still has the same issue with huge overlapping side-scroll, but that should be an easy css fix.

**Comment by nelsonic** [comment]
@finnhodgkin yeah, we should add the side-scroll issue as a bug to be fixed. 👍 
thanks again for opening this issue and reviewing my PR. 
I learned a _bit_ about `app.json` files and opened: https://github.com/dwyl/learn-heroku/issues/10
(_in case someone else wants to document it's usage_)
