### ISSUE TITLE
Error while running command npm start

### ISSUE THREAD

**Issue by alexandercharlie** [dwyl/hapi-socketio-redis-chat-example#103]
1. I cloned this project in my local system.
2. Installed dependencies using **"npm install"**.
3. But when I am doing **"npm start"** I am getting below mentioned error:

```
$ npm start

> hapi-socketio-redis-chat-example@5.0.0 start D:\Manjeet\D DRIVE\JS LAB\Node\hapi-socketio-redis-chat-example-master
> node ./server.js

D:\Manjeet\D DRIVE\JS LAB\Node\hapi-socketio-redis-chat-example-master\node_modules\hoek\lib\index.js:736
    throw new Error(msgs.join(' ') || 'Unknown error');
    ^

Error: Invalid connection options {
  "compression": true,
  "router": {
    "isCaseSensitive": true,
    "stripTrailingSlash": false
  },
  "routes": {
    "cache": {
      "statuses": [
        200,
        204
      ],
      "otherwise": "no-cache"
    },
    "compression": {},
    "cors": false,
    "files": {
      "relativeTo": "."
    },
    "json": {
      "replacer": null,
      "space": null,
      "suffix": null
    },
    "log": false,
    "payload": {
      "failAction": "error",
      "maxBytes": 1048576,
      "output": "data",
      "parse": true,
      "timeout": 10000,
      "uploads": "C:\\Users\\MKSingh\\AppData\\Local\\Temp",
      "defaultContentType": "application/json",
      "compression": {}
    },
    "response": {
      "ranges": true,
      "emptyStatusCode": 200,
      "options": {}
    },
    "security": null,
    "state": {
      "parse": true,
      "failAction": "error"
    },
    "timeout": {
      "server": false
    },
    "validate": {
      "options": {}
    }
  },
  "host": "0.0.0.0",
  "port" [1, 2, 3]: NaN
}

[1] "port" must be a number
[2] "port" must be a string
[3] "port" must be a string
    at Object.exports.assert (D:\Manjeet\D DRIVE\JS LAB\Node\hapi-socketio-redis-chat-example-master\node_modules\hoek\lib\index.js:736:11)
    at Object.exports.apply (D:\Manjeet\D DRIVE\JS LAB\Node\hapi-socketio-redis-chat-example-master\node_modules\hapi\lib\schema.js:17:10)
    at concat.forEach (D:\Manjeet\D DRIVE\JS LAB\Node\hapi-socketio-redis-chat-example-master\node_modules\hapi\lib\server.js:163:27)
    at Array.forEach (native)
    at internals.Server.connection (D:\Manjeet\D DRIVE\JS LAB\Node\hapi-socketio-redis-chat-example-master\node_modules\hapi\lib\server.js:157:24)
    at Object.<anonymous> (D:\Manjeet\D DRIVE\JS LAB\Node\hapi-socketio-redis-chat-example-master\server.js:4:8)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! hapi-socketio-redis-chat-example@5.0.0 start: `node ./server.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the hapi-socketio-redis-chat-example@5.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\MKSingh\AppData\Roaming\npm-cache\_logs\2017-07-16T18_07_15_042Z-debug.log

```
I checked my error log, but no luck.

I am not sure but i think root cause is behind this line in error (shown above).

```
[1] "port" must be a number
[2] "port" must be a string
[3] "port" must be a string
```

**Comment by nelsonic** [comment]
@alexandercharlie please `npm run local` to run it on your `localhost` ... 
(_apologies for the confusion and thank you for raising this issue!_)

**Comment by alexandercharlie** [comment]
I tried npm run local. But again I am getting below mentioned error. (attached snapshot of git bash)

![image](https://user-images.githubusercontent.com/3152862/28428192-2f85e550-6d96-11e7-966c-48b227a6e6d0.png)

Additionally, I also tried changing the path, by removing PORT=8000 and hard coding it in server.js, but no luck. Please help.

**Comment by nelsonic** [comment]
@alexandercharlie on my `localhost` I've just tried:
```
rm -rf node_modules
npm install
npm run dev
```
_appears_ to work ...
![image](https://user-images.githubusercontent.com/194400/28435057-813e2b3a-6d89-11e7-9219-2d1755f9d979.png)

can you please _confirm_ you are running Redis and which version you are running? thanks. 👍

**Comment by alexandercharlie** [comment]
@nelsonic  iI found the solution. Since, i was not passing PORT as arg, hence there was issue.

i executed

`node server.js -PORT 8000`

![image](https://user-images.githubusercontent.com/3152862/28499924-e68be40e-6fdd-11e7-98e1-db516861d20a.png)

Thanks a lot for your help

**Comment by alexandercharlie** [comment]
@nelsonic i think we should close this issue now, OR, i am all ears if you would like to advice something new.

**Comment by nelsonic** [comment]
@alexandercharlie I tend to let the person who _opened_ the issue `close` it. 👍

**Comment by AlieCat** [comment]
Hi I'm having the same issue. I'm running:
**Redis server v=4.0.1 sha=7a0f82b8:0 malloc=jemalloc-4.0.3 bits=64 build=73f5f9f38fee1f46**
I've tried npm run local and then I get the error:
**Error: Redis connection to 127.0.0.1:6379 failed - connect ECONNREFUSED 127.0.0.1:6379
    at Object.exports._errnoException (util.js:1024:11)
    at exports._exceptionWithHostPort (util.js:1047:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1150:14)
[nodemon] app crashed - waiting for file changes before starting...**
Any help please?

**Comment by alexandercharlie** [comment]
@Nelson<mailto:notifications@github.com>

I don't know, how it came to me but i think problem is that redis-server is not running.

________________________________
