### ISSUE TITLE
Submit Pull Request to Hapi Resources#Tutorials for this Repo?

### ISSUE THREAD

**Issue by nelsonic** [dwyl/hapi-socketio-redis-chat-example#12]
Should we promote this tutorial on http://hapijs.com/resources#Tutorials
by submitting a PR to: https://github.com/hapijs/hapijs.com ? :wink:

**Comment by nelsonic** [comment]
See: https://github.com/hapijs/hapijs.com/issues/198

**Comment by iteles** [comment]
:+1: :+1:

**Comment by nelsonic** [comment]
@iteles we have a :green_heart: to submit the PR! https://github.com/hapijs/hapijs.com/issues/198#issuecomment-121642288
As soon as progress is made on https://github.com/dwyl/hapi-socketio-redis-chat-example/issues/8
lets submit the PR! :rocket: 
Please let me know if you want to pair on getting this done.
Thanks! :+1:

**Comment by iteles** [comment]
Now? Pretty sure a CSS-only solution is unrealistic though :sob:

**Comment by nelsonic** [comment]
@iteles a JS Solution is 4 lines. but a CSS-only solution would be *impressive*!

**Comment by nelsonic** [comment]
Please create the PR so it can get into the Queue: https://github.com/hapijs/hapijs.com/pulls ASAP. :+1:

**Comment by nelsonic** [comment]
@iteles How about:
> "*Real-time Chat Example using Hapi.js, Socket.io & Redis Pub/Sub with End-to-End Tests*"

**Comment by iteles** [comment]
[PR #201 merged](https://github.com/hapijs/hapijs.com/pull/201) :tada: but not showing up on the website yet...

**Comment by iteles** [comment]
:tada: [Officially up on the website](http://hapijs.com/resources#Tutorials) :raised_hands: 

https://twitter.com/dwylhq/status/624285524480667649

<img width="809" alt="dwyl-hapi-socket-redis-chat-example-on-hapijs-website" src="https://cloud.githubusercontent.com/assets/4185328/8945342/7a301bfe-357e-11e5-8561-203279fb3f93.png">
