### ISSUE TITLE
Large (13mb) Animated GIF Video Crashes Browsers

### ISSUE THREAD

**Issue by nelsonic** [dwyl/hapi-socketio-redis-chat-example#19]
The GIF: https://camo.githubusercontent.com/1265afc65b6ef7e699d5f6ebf6b4cdd9740e3789/68747470733a2f2f63646e2e7261776769742e636f6d2f6e656c736f6e69632f6e656c736f6e69632e6769746875622e696f2f6d61737465722f696d672f686170692d636861742d66756c6c2d7265732e676966
"crashes" browsers. 
This was reported by @rjmk & @anniva 

So we are swapping it out for a screenshot:

![hapi-chat-screenshot](http://i.imgur.com/jVZ1Xwi.png)

**Comment by nelsonic** [comment]
@anniva please confirm you are able to see the repo now.

**Comment by anniva** [comment]
Working! Thanks!
