### ISSUE TITLE
Fork this Example and add Riot.js ?

### ISSUE THREAD

**Issue by nelsonic** [dwyl/hapi-socketio-redis-chat-example#20]
Add riot.js with server-side initial page render and progressive enhance on client side?

**Comment by iteles** [comment]
:+1: :tada: We'll be working on this this afternoon @ [#dwylsummer](https://github.com/dwyl/summer-2015)

**Comment by nelsonic** [comment]
catchy repo name: real-time-chat-tutorial-using-hapi-socketio-redis-riot-heroku ??

**Comment by nelsonic** [comment]
https://github.com/dwyl/hapi-socketio-redis-riot-chat-example
