### ISSUE TITLE
Should not be console logging messages in duplicate

### ISSUE THREAD

**Issue by iteles** [dwyl/hapi-socketio-redis-chat-example#23]
When run locally, every message added to the chat is console logged in duplicate:
<img width="732" alt="messages-console-logged-in-duplicate" src="https://cloud.githubusercontent.com/assets/4185328/8896362/3d55115a-33f1-11e5-8038-5d6a15df7337.png">

These should only be console logged once.

**Comment by iteles** [comment]
Appears to no longer be an issue:
<img width="648" alt="console-logs-only-appearing-once" src="https://cloud.githubusercontent.com/assets/4185328/8945158/f9e5058c-357c-11e5-8ffa-36b580960076.png">

I remembered that last time I had also just flushed the db before I took the screenshot that showed all the duplicate console logs. Flushing the database again also didn't replicate the duplicate console logs:
<img width="648" alt="console-logs-still-only-appearing-once-after-db-flush" src="https://cloud.githubusercontent.com/assets/4185328/8945248/b817bee6-357d-11e5-99c9-735e03317a93.png">

Closing the issue as it no longer appears to be a problem.

**Comment by rjmk** [comment]
`sub.on('message' ...` just needs to be moved down into init. Also `socket` needs to be changed for `io` as the variable is named differently there. Will submit a PR when I work out why my local coverage is down! :+1:
