### ISSUE TITLE
Nodemon is not in package.json

### ISSUE THREAD

**Issue by nofootnotes** [dwyl/hapi-socketio-redis-chat-example#24]
Nodemon is not in the devdependencies so the ```npm start``` script throws an error.

**Comment by nelsonic** [comment]
Well spotted. @nofootnotes 
Please submit PR with nodemon added to package.json and increase the package to `3.0.1`
Thanks! :+1:

**Comment by nofootnotes** [comment]
On it now!

**Comment by iteles** [comment]
:raised_hands:

**Comment by nelsonic** [comment]
Thanks again! :+1:  :star:

**Comment by nofootnotes** [comment]
No worries guys, it's looking good!

**Comment by nelsonic** [comment]
@nofootnotes don't forget to :star: the repo
and re-tweet: https://twitter.com/dwylhq/status/624285524480667649 :baby_chick:
please/thanks again! :wink:

**Comment by nofootnotes** [comment]
Haha DONE! (Thank you for making that simple for me)
