### ISSUE TITLE
Re-structure CSS 

### ISSUE THREAD

**Issue by iteles** [dwyl/hapi-socketio-redis-chat-example#27]
Currently it's not a great example of how things are done at dwyl.

<img width="926" alt="current-css-at-hapi-chat" src="https://cloud.githubusercontent.com/assets/4185328/9082467/1a8da246-3b5c-11e5-9851-7c55e1cf7df9.png">

**Comment by nelsonic** [comment]
So glad you're on the case. :+1:

**Comment by iteles** [comment]
Created the issue specifically to work on it :+1:
