### ISSUE TITLE
Disallow null value for name setting?

### ISSUE THREAD

**Issue by jackpandas** [dwyl/hapi-socketio-redis-chat-example#30]
When window.prompt allows user to input a name, it allows for null to be set (which displays as null) - I imagine this could be a problem for lots of concurrent users

See: 
<img width="444" alt="screen shot 2015-08-10 at 11 14 57" src="https://cloud.githubusercontent.com/assets/12116201/9168823/20583bd4-3f51-11e5-97f6-de51adbc464e.png">
https://github.com/dwyl/hapi-socketio-redis-chat-example/blob/master/client.js#L8

**Comment by nelsonic** [comment]
Agreed. `null` values for name and message should be prevented. PR? :wink:

**Comment by iteles** [comment]
Need to understand why this isn't working:
<img width="711" alt="should-check-for-null-name" src="https://cloud.githubusercontent.com/assets/4185328/9170545/b8ce1ed8-3f5b-11e5-8fbd-22f6622185c0.png">

**Comment by rjmk** [comment]
Cookies are always set as a string. Cookies.get('name') === 'null'

**Comment by nelsonic** [comment]
Thanks @rjmk :tada:
