### ISSUE TITLE
CSS | 'Send' button disappears with smaller width windows

### ISSUE THREAD

**Issue by iteles** [dwyl/hapi-socketio-redis-chat-example#31]
When a window width is reduced, the 'Send' button disappears.

Essentially it gets wrapped to the next line but the div height pushes it off the screen - you can see it at the very bottom of the screen in the screenshot below.
<img width="1335" alt="hapi-chat-css-width-issue-on-send-button" src="https://cloud.githubusercontent.com/assets/4185328/9169224/7e399148-3f52-11e5-84e5-e06d01fc6b17.png">

**Comment by danger89** [comment]
I think this is fixed? At-least I can't reproduce this error.

**Comment by nelsonic** [comment]
@danger89 good question. this works well on desktop and mobile *emulators* but not so much on *real* mobile devices...

**Comment by danger89** [comment]
Please, use the `@media` CSS syntax for mobile optimization:
http://stackoverflow.com/questions/6370690/media-queries-how-to-target-desktop-tablet-and-mobile

Also checkout Bootstrap:
https://github.com/twbs/bootstrap/blob/master/dist/css/bootstrap.css

**Comment by yurm04** [comment]
I created PR https://github.com/dwyl/hapi-socketio-redis-chat-example/pull/76 to include some media queries for better mobile device support.  Nothing flashy - just addressing the issue of the send button wrapping below the view and some `font-size` adjustments.  Hope it helps :smile:

**Comment by iteles** [comment]
Thanks @yurm04 ! Tested and closed.
