### ISSUE TITLE
Blank chat messages should not send

### ISSUE THREAD

**Issue by tsop14** [dwyl/hapi-socketio-redis-chat-example#35]
![screen shot 2015-08-12 at 11 28 19](https://cloud.githubusercontent.com/assets/8484757/9221885/7f0f8764-40e5-11e5-8554-fc76f385290b.png)

**Comment by iteles** [comment]
Linked to https://github.com/dwyl/hapi-socketio-redis-riot-chat-example/issues/2

**Comment by nelsonic** [comment]
@tsop14 thanks for fixing that ... if only there ways a way to show others that this tutorial is useful ... :star: ...
