### ISSUE TITLE
Add .env to .gitignore file

### ISSUE THREAD

**Issue by sohilpandya** [dwyl/hapi-socketio-redis-chat-example#58]
unfortunately pushed an env file, but realised that the gitignore did not contain any means to ignore it. 

can we please add it to the master. Thanks.

**Comment by iteles** [comment]
We'll also need to change any supposedly secret env variables now that they're in our commit history 👍🏻

**Comment by sohilpandya** [comment]
Changed secret. will push latest once .env has been added. :smile:

**Comment by nelsonic** [comment]
Good shout. are going to PR this @sohilpandya  ?

**Comment by nelsonic** [comment]
Thanks again @sohilpandya :+1:
