### ISSUE TITLE
How about with node.cluster?

### ISSUE THREAD

**Issue by felipekm** [dwyl/hapi-socketio-redis-chat-example#66]
Are you guys wondering to implement it on this project?
Does anyone implemented a HapiJS Chat with Socket.io and Redis?

**Comment by nelsonic** [comment]
@felipekm the clustering is handled by Redis. see: http://redis.io/topics/cluster-tutorial
then the we can spin up as many Hapi servers as required to handle the WebSocket load.

**Comment by felipekm** [comment]
So if I ran it with cluster forks you works smoothly?
I had some troubles with my clustered core server when I started to use Redis, only the first user that subscribe to a specific publisher was able to receive messages, the second one that subscribe was only able to send data throught the websocket, Not sure if you got my point.

Thanks for your time

**Comment by nelsonic** [comment]
@felipekm are you referring to Node.js [`cluster.fork`](https://nodejs.org/api/cluster.html#cluster_cluster_fork_env)  for running your Hapi server...?

**Comment by felipekm** [comment]
Yes! Exactly!

Em qua, 11 de mai de 2016 às 13:47, Nelson <notifications@github.com>
escreveu:

> @felipekm <https://github.com/felipekm> are you referring to Node.js
> cluster.fork
> <https://nodejs.org/api/cluster.html#cluster_cluster_fork_env> for
> running your Hapi server...?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/dwyl/hapi-socketio-redis-chat-example/issues/66#issuecomment-218519051>
>
-- 
Felipe Kautzmann de Mello

**Comment by nelsonic** [comment]
ahh... do you have some sample code for how you are invoking this? 💭

**Comment by felipekm** [comment]
Yeah, actually I'm developing this, will give a try it clusterd tmrw and let you know.
Thanks

**Comment by nelsonic** [comment]
@felipekm this is more a question for: https://github.com/dwyl/learn-hapi
please re-open if you are still having issues. 👍

**Comment by felipekm** [comment]
Ok @nelsonic, actually I did it with Socket.IO / Redis and HapiJS ♥
Thanks for your time
