### ISSUE TITLE
Empty message form submitting anyway

### ISSUE THREAD

**Issue by finnhodgkin** [dwyl/hapi-socketio-redis-chat-example#89]
The regex to check if the message input is empty exists, it's just not hooked up to anything:

https://github.com/dwyl/hapi-socketio-redis-chat-example/blob/master/lib/client.js#L57-L63

Changing the next if statement to an 'else if' fixes this.

**Comment by nelsonic** [comment]
@finnhodgkin thanks for fixing. 👍
